service:
  host: 34.82.27.240
  port: 5432
  user: postgres
  password: "{qqo0QGf*[a+KCs="
  database: postgres
  client_cert: "cert/client-cert.pem"
  client_key: "cert/client-key.pem"
  server_cert: "cert/server-ca.pem"
frequency:
  frequency: 5
  max_peak: 10
